// Generated for: node-dotnet-sample 0.0.0.0
// Generated by: Microsoft.JavaScript.NodeApi.Generator 0.5.0.0
/* eslint-disable */


declare module 'node-api-dotnet' {

	export namespace Sample {
		export class Generator {
			constructor();

			static GeneratePluginAsync(
				spec: string,
				pluginName: string,
				namespaceName: string,
				includePatterns: string,
				excludePatterns: string,
			): Promise<string>;
		}
	}
}

declare module 'node-dotnet-sample' {
	export * from 'node-api-dotnet';
}

export * from 'node-api-dotnet';
